language: c
compiler:
  - gcc
notifications:
  recipients:
    - kaian@irontec.com
before_script:
    - sudo apt-get update
install:
    - sudo apt-get install -y dh-autoreconf cmake debhelper libedit-dev libconfig-dev unixodbc-dev libglib2.0-dev
script: 
    - cmake .
    - make
branches:
  only:
    - master
