/**
 * Isaac -- Ivozng simplified Asterisk AMI Connector
 *
 * Copyright (C) 2013 Irontec S.L.
 * Copyright (C) 2013 Ivan Alonso (aka Kaian)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef __ISAAC_APP_H
#define __ISAAC_APP_H
#include "session.h"

/** 
 * \brief Common exit codes for applications.
 * If your application returns any of this common errors, corresponding
 * message generated by apperr2str will be send trough the session 
 * connection.
 * This codes are all negative and start at 400 to avoid being used by
 * mistake.
 */
enum apperr
{
    NOT_AUTHENTICATED = -400,
    UNKOWN_ACTION = -401,
    INVALID_ARGUMENTS = -402,
    INVALID_FORMAT = -403,
};

/* Application structure */
struct app
{
    char *name; // App exec name
    int (*execute)(session_t *sess, const char *args); // App exec function

    struct app *next; // Next application in the list
};
typedef struct app app_t; // Application type for easy coding

/**
 *
 **/
int application_register(const char *name, int(*execute)(session_t *sess, const char *args));

/**
 *
 **/
int application_unregister(const char *name);

/**
 *
 **/
app_t *application_find(const char *name);

/**
 *
 **/
int application_run(app_t *app, session_t *sess, const char *args);

/**
 *
 **/
const char *apperr2str(int apperr);

#endif
